name: Main
on:
  push:
    branches:
      - "main"

permissions:
  contents: read
  packages: write

env:
  ENVIRONMENT: 'development'
  # Pinning the humctl version individually for each workflow to be able to test a version bump
  HUMCTL_VERSION: '0.24.0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: humanitec/setup-cli-action@v1
        with:
          version: ${{ env.HUMCTL_VERSION }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        id: build_push
        run: |
          # Make sure repo name is all lowercase for docker push
          GH_REPOSITORY=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')

          TAG=$GH_REPOSITORY:latest
          IMAGE=ghcr.io/$TAG

          # Set this label to connect the package to the GitHub repo to make it public
          docker build . --tag $IMAGE  \
            --label "org.opencontainers.image.source=https://github.com/$GH_REPOSITORY"
          docker push $IMAGE

          # Get image digest to pass on to deployment for pinning the image to that digest
          IMAGE_DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' $IMAGE)
          echo "IMAGE_DIGEST=$IMAGE_DIGEST" >> $GITHUB_OUTPUT

      - name: Deploy Score
        run: |
          humctl score deploy \
              --token ${{ secrets.HUMANITEC_TOKEN }} \
              --org ${{ vars.HUMANITEC_ORG }} \
              --app ${{ vars.HUMANITEC_APP }} \
              --env ${{ env.ENVIRONMENT }} \
              --message "$(git show -s --format=%s)" \
              -f score.yaml \
              --image ${{ steps.build_push.outputs.IMAGE_DIGEST }}
